local returnedData = [[

{
  "version": 1,
  "status": "ok",
  "source": "openstreetmap",
  "attribution": "© OpenStreetMap contributors",
  "origin": {
    "lat": 56.9500238,
    "lon": 24.0999654
  },
  "chunk": {
    "x": 0,
    "z": 0,
    "size": 256,
    "minX": -128,
    "minZ": -128,
    "maxX": 128,
    "maxZ": 128
  },
  "stats": {
    "roads": 85,
    "buildings": 21,
    "water": 2,
    "landuse": 26,
    "trees": 73,
    "pois": 7,
    "cache": "miss"
  },
  "roads": [
    {
      "id": "way/4950960",
      "class": "residential",
      "width": 9,
      "surface": "asphalt",
      "name": "Poļu gāte",
      "points": [
        [
          33.2,
          0,
          -21.3
        ],
        [
          43.6,
          0,
          -15.4
        ]
      ]
    },
    {
      "id": "way/26413472",
      "class": "living_street",
      "width": 4,
      "surface": "sett",
      "name": "Miesnieku iela",
      "points": [
        [
          224.2,
          0,
          -0.7
        ],
        [
          200.5,
          0,
          -25.7
        ],
        [
          176.9,
          0,
          -47.6
        ],
        [
          123.9,
          0,
          -93.7
        ]
      ]
    },
    {
      "id": "way/26561164",
      "class": "residential",
      "width": 5,
      "surface": "sett",
      "name": "11. novembra krastmala",
      "points": [
        [
          163,
          0,
          -178.8
        ],
        [
          59.9,
          0,
          -6.2
        ]
      ]
    },
    {
      "id": "way/26561228",
      "class": "living_street",
      "width": 4,
      "surface": "sett",
      "name": "Anglikāņu iela",
      "points": [
        [
          152,
          0,
          19.4
        ],
        [
          138.4,
          0,
          -0.3
        ],
        [
          132.4,
          0,
          -6.6
        ],
        [
          93.6,
          0,
          -30.2
        ]
      ]
    },
    {
      "id": "way/26561255",
      "class": "steps",
      "width": 5,
      "surface": "concrete",
      "name": null,
      "points": [
        [
          95,
          0,
          -42.8
        ],
        [
          92.9,
          0,
          -44.1
        ]
      ]
    },
    {
      "id": "way/29974581",
      "class": "living_street",
      "width": 8,
      "surface": "sett",
      "name": "Pils iela",
      "points": [
        [
          229.2,
          0,
          -2.2
        ],
        [
          152,
          0,
          19.4
        ],
        [
          125.5,
          0,
          31.8
        ]
      ]
    },
    {
      "id": "way/38917036",
      "class": "living_street",
      "width": 4,
      "surface": "sett",
      "name": "Pils iela",
      "points": [
        [
          125.5,
          0,
          31.8
        ],
        [
          110.6,
          0,
          77.8
        ],
        [
          101.9,
          0,
          91.6
        ]
      ]
    },
    {
      "id": "way/39346851",
      "class": "living_street",
      "width": 4,
      "surface": "sett",
      "name": "Mazā Pils iela",
      "points": [
        [
          136.8,
          0,
          83.8
        ],
        [
          110.6,
          0,
          77.8
        ]
      ]
    },
    {
      "id": "way/39348069",
      "class": "pedestrian",
      "width": 4,
      "surface": "asphalt",
      "name": "Daugavas gāte",
      "points": [
        [
          94.7,
          0,
          65
        ],
        [
          81.3,
          0,
          64.1
        ],
        [
          49.2,
          0,
          46.8
        ],
        [
          18.8,
          0,
          28.8
        ]
      ]
    },
    {
      "id": "way/44954751",
      "class": "living_street",
      "width": 4,
      "surface": "asphalt",
      "name": "Pils laukums",
      "points": [
        [
          101.9,
          0,
          91.6
        ],
        [
          75,
          0,
          146.1
        ],
        [
          60.3,
          0,
          173.8
        ]
      ]
    },
    {
      "id": "way/81142345",
      "class": "residential",
      "width": 5,
      "surface": "sett",
      "name": "Miesnieku iela",
      "points": [
        [
          123.9,
          0,
          -93.7
        ],
        [
          115.9,
          0,
          -100.6
        ]
      ]
    },
    {
      "id": "way/114254061",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          -82.6,
          0,
          162.2
        ],
        [
          -65.1,
          0,
          111.7
        ],
        [
          -51.7,
          0,
          77.1
        ],
        [
          -14.9,
          0,
          -8.4
        ],
        [
          -7.8,
          0,
          -23.3
        ],
        [
          -6.8,
          0,
          -24.7
        ],
        [
          -1.3,
          0,
          -26.6
        ],
        [
          -0.3,
          0,
          -27.8
        ],
        [
          10.5,
          0,
          -50.1
        ],
        [
          8.4,
          0,
          -56.5
        ],
        [
          9,
          0,
          -57.9
        ],
        [
          39.5,
          0,
          -114.1
        ],
        [
          69.8,
          0,
          -167.6
        ],
        [
          93.2,
          0,
          -204.4
        ]
      ]
    },
    {
      "id": "way/135346983",
      "class": "living_street",
      "width": 6,
      "surface": "sett",
      "name": "Poļu gāte",
      "points": [
        [
          59.9,
          0,
          -6.2
        ],
        [
          117.2,
          0,
          26.2
        ],
        [
          125.5,
          0,
          31.8
        ]
      ]
    },
    {
      "id": "way/135466076",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          75.5,
          0,
          164.1
        ],
        [
          106.4,
          0,
          96.4
        ],
        [
          108.8,
          0,
          93.8
        ],
        [
          112.1,
          0,
          92.7
        ],
        [
          134.5,
          0,
          98.7
        ],
        [
          138,
          0,
          104.3
        ],
        [
          141.8,
          0,
          180.7
        ],
        [
          75.5,
          0,
          164.1
        ]
      ]
    },
    {
      "id": "way/135466077",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          -51.8,
          0,
          249.8
        ],
        [
          -46.4,
          0,
          225.1
        ],
        [
          -37.8,
          0,
          219.4
        ],
        [
          -27.3,
          0,
          180
        ],
        [
          -26.3,
          0,
          117.9
        ],
        [
          -22.9,
          0,
          102.9
        ],
        [
          -20.3,
          0,
          95.8
        ],
        [
          -13.6,
          0,
          82.9
        ],
        [
          -7.1,
          0,
          73.2
        ],
        [
          18.8,
          0,
          28.8
        ],
        [
          40.4,
          0,
          -9.9
        ],
        [
          43.3,
          0,
          -10.2
        ],
        [
          61.8,
          0,
          0.8
        ]
      ]
    },
    {
      "id": "way/135466078",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          64.4,
          0,
          -3.7
        ],
        [
          38.1,
          0,
          40.2
        ],
        [
          37.4,
          0,
          43.1
        ]
      ]
    },
    {
      "id": "way/157821296",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          3,
          0,
          -34.1
        ],
        [
          9.3,
          0,
          -31.2
        ]
      ]
    },
    {
      "id": "way/169683884",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          -2.2,
          0,
          -34.1
        ],
        [
          4.7,
          0,
          -48.9
        ]
      ]
    },
    {
      "id": "way/169683889",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          -5.2,
          0,
          -35.7
        ],
        [
          1.8,
          0,
          -50.3
        ]
      ]
    },
    {
      "id": "way/169683890",
      "class": "steps",
      "width": 5,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          12.4,
          0,
          -29.7
        ],
        [
          9.3,
          0,
          -31.2
        ]
      ]
    },
    {
      "id": "way/169683892",
      "class": "steps",
      "width": 5,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          9.1,
          0,
          -46.8
        ],
        [
          1.8,
          0,
          -50.3
        ]
      ]
    },
    {
      "id": "way/169683893",
      "class": "steps",
      "width": 5,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          1.9,
          0,
          -31.8
        ],
        [
          -5.2,
          0,
          -35.7
        ]
      ]
    },
    {
      "id": "way/169683894",
      "class": "service",
      "width": 3,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          -34.7,
          0,
          103.2
        ],
        [
          -37.2,
          0,
          122.2
        ],
        [
          -44.4,
          0,
          161.2
        ]
      ]
    },
    {
      "id": "way/169683895",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          40.4,
          0,
          -9.9
        ],
        [
          48.8,
          0,
          -22.8
        ],
        [
          140.5,
          0,
          -184.3
        ],
        [
          142.8,
          0,
          -185.5
        ],
        [
          145.2,
          0,
          -183.6
        ],
        [
          149.2,
          0,
          -189.9
        ]
      ]
    },
    {
      "id": "way/169683896",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          12.4,
          0,
          -29.7
        ],
        [
          14.4,
          0,
          -28.7
        ],
        [
          19.9,
          0,
          -38.5
        ],
        [
          48.8,
          0,
          -22.8
        ]
      ]
    },
    {
      "id": "way/169689425",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          12.8,
          0,
          136.2
        ],
        [
          12.3,
          0,
          137.2
        ],
        [
          -16.2,
          0,
          125.3
        ],
        [
          -5.2,
          0,
          84.4
        ],
        [
          8.7,
          0,
          86.5
        ]
      ]
    },
    {
      "id": "way/169689426",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          -16.9,
          0,
          93.9
        ],
        [
          -20.3,
          0,
          102.8
        ],
        [
          -23.4,
          0,
          117.3
        ],
        [
          -23.7,
          0,
          132.6
        ],
        [
          -22.1,
          0,
          135.6
        ],
        [
          -6,
          0,
          147.7
        ],
        [
          7.6,
          0,
          154.3
        ]
      ]
    },
    {
      "id": "way/169689435",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          37.4,
          0,
          48.6
        ],
        [
          37.8,
          0,
          51.1
        ]
      ]
    },
    {
      "id": "way/169689436",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          -15,
          0,
          90.3
        ],
        [
          -16.9,
          0,
          93.9
        ]
      ]
    },
    {
      "id": "way/169689438",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          37.4,
          0,
          43.1
        ],
        [
          39.8,
          0,
          44.5
        ]
      ]
    },
    {
      "id": "way/169689440",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          37.4,
          0,
          48.6
        ],
        [
          35,
          0,
          49.4
        ]
      ]
    },
    {
      "id": "way/169689441",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          26,
          0,
          123.7
        ],
        [
          26.6,
          0,
          122.5
        ]
      ]
    },
    {
      "id": "way/169689444",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          17,
          0,
          128.2
        ],
        [
          15.5,
          0,
          125.8
        ],
        [
          -2.8,
          0,
          118
        ],
        [
          1,
          0,
          108.2
        ],
        [
          5.9,
          0,
          107
        ],
        [
          7.1,
          0,
          105.3
        ],
        [
          10.1,
          0,
          105.8
        ],
        [
          13.5,
          0,
          104.9
        ],
        [
          16,
          0,
          102.8
        ],
        [
          19,
          0,
          102.3
        ],
        [
          22.9,
          0,
          103.4
        ],
        [
          32.6,
          0,
          110.4
        ],
        [
          38.6,
          0,
          113.3
        ],
        [
          54.8,
          0,
          123.5
        ],
        [
          56.4,
          0,
          127.9
        ],
        [
          52.9,
          0,
          134.5
        ],
        [
          48.2,
          0,
          136.3
        ],
        [
          46.3,
          0,
          140.4
        ],
        [
          26.1,
          0,
          131.8
        ],
        [
          28.2,
          0,
          127.1
        ]
      ]
    },
    {
      "id": "way/169689445",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          24.2,
          0,
          127.7
        ],
        [
          26,
          0,
          123.7
        ]
      ]
    },
    {
      "id": "way/169689447",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          15.5,
          0,
          125.8
        ],
        [
          14.9,
          0,
          123.4
        ],
        [
          16.4,
          0,
          120.7
        ]
      ]
    },
    {
      "id": "way/169689448",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          37.9,
          0,
          52.5
        ],
        [
          33.3,
          0,
          50.1
        ],
        [
          35,
          0,
          49.4
        ]
      ]
    },
    {
      "id": "way/169689449",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          39.8,
          0,
          44.5
        ],
        [
          37.4,
          0,
          48.6
        ]
      ]
    },
    {
      "id": "way/169689450",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          42.9,
          0,
          99.7
        ],
        [
          56.6,
          0,
          79.2
        ]
      ]
    },
    {
      "id": "way/169689451",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          55.6,
          0,
          80.7
        ],
        [
          48.6,
          0,
          75.9
        ],
        [
          38.9,
          0,
          91.2
        ]
      ]
    },
    {
      "id": "way/169689452",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          69.9,
          0,
          84.3
        ],
        [
          47.4,
          0,
          70.9
        ],
        [
          33.3,
          0,
          93.1
        ]
      ]
    },
    {
      "id": "way/169689455",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          47.9,
          0,
          92.7
        ],
        [
          37.9,
          0,
          86.1
        ]
      ]
    },
    {
      "id": "way/169689456",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          66,
          0,
          62.9
        ],
        [
          58.7,
          0,
          73.4
        ],
        [
          56.6,
          0,
          79.2
        ]
      ]
    },
    {
      "id": "way/169689459",
      "class": "service",
      "width": 3,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          53.9,
          0,
          135
        ],
        [
          28.2,
          0,
          127.1
        ],
        [
          14.9,
          0,
          119.8
        ],
        [
          12.5,
          0,
          116.3
        ]
      ]
    },
    {
      "id": "way/169689460",
      "class": "service",
      "width": 3,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          12.5,
          0,
          116.3
        ],
        [
          14.6,
          0,
          111.9
        ],
        [
          18.1,
          0,
          110
        ],
        [
          25.2,
          0,
          112.2
        ],
        [
          30.3,
          0,
          115.3
        ],
        [
          39.4,
          0,
          124.8
        ],
        [
          46.7,
          0,
          131.1
        ],
        [
          52.9,
          0,
          134.5
        ]
      ]
    },
    {
      "id": "way/169689480",
      "class": "primary",
      "width": 10,
      "surface": "asphalt",
      "name": "11. novembra krastmala",
      "points": [
        [
          -34.7,
          0,
          103.2
        ],
        [
          -45.5,
          0,
          132.2
        ],
        [
          -56.4,
          0,
          167.8
        ]
      ]
    },
    {
      "id": "way/172640998",
      "class": "primary",
      "width": 10,
      "surface": "asphalt",
      "name": "11. novembra krastmala",
      "points": [
        [
          140.5,
          0,
          -206.6
        ],
        [
          126.7,
          0,
          -186.6
        ],
        [
          -14.2,
          0,
          61.1
        ],
        [
          -25.9,
          0,
          82.8
        ],
        [
          -34.7,
          0,
          103.2
        ]
      ]
    },
    {
      "id": "way/223782879",
      "class": "primary",
      "width": 10,
      "surface": "asphalt",
      "name": "11. novembra krastmala",
      "points": [
        [
          -68.9,
          0,
          164.2
        ],
        [
          -63.2,
          0,
          145.1
        ],
        [
          -52,
          0,
          117.6
        ],
        [
          -45,
          0,
          102
        ],
        [
          -33.2,
          0,
          79.7
        ],
        [
          29.6,
          0,
          -33.3
        ],
        [
          69.1,
          0,
          -102.7
        ],
        [
          132.9,
          0,
          -211.2
        ],
        [
          182.5,
          0,
          -299.9
        ]
      ]
    },
    {
      "id": "way/232822081",
      "class": "footway",
      "width": 2,
      "surface": "sett",
      "name": null,
      "points": [
        [
          95,
          0,
          -42.8
        ],
        [
          99.4,
          0,
          -40.3
        ],
        [
          93.6,
          0,
          -30.2
        ],
        [
          88.9,
          0,
          -30.7
        ],
        [
          84.6,
          0,
          -23.6
        ]
      ]
    },
    {
      "id": "way/232822088",
      "class": "footway",
      "width": 2,
      "surface": "sett",
      "name": null,
      "points": [
        [
          83.4,
          0,
          -15.5
        ],
        [
          85,
          0,
          -12.8
        ],
        [
          83.9,
          0,
          -10.8
        ],
        [
          79.6,
          0,
          -13.3
        ],
        [
          80.7,
          0,
          -15.1
        ],
        [
          83.4,
          0,
          -15.5
        ],
        [
          84.1,
          0,
          -16.7
        ]
      ]
    },
    {
      "id": "way/232822090",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          74,
          0,
          -29.6
        ],
        [
          82,
          0,
          -25
        ]
      ]
    },
    {
      "id": "way/300930402",
      "class": "cycleway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          -559.3,
          0,
          13.4
        ],
        [
          -466.5,
          0,
          45.9
        ],
        [
          -465.6,
          0,
          43.8
        ],
        [
          -461.4,
          0,
          43.9
        ],
        [
          -458.4,
          0,
          46.4
        ],
        [
          -458.7,
          0,
          48.7
        ],
        [
          -31,
          0,
          200.4
        ],
        [
          -23.5,
          0,
          204.2
        ],
        [
          68,
          0,
          236.8
        ]
      ]
    },
    {
      "id": "way/311545259",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          114.3,
          0,
          -86.2
        ],
        [
          92.9,
          0,
          -100.5
        ]
      ]
    },
    {
      "id": "way/311545260",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          88.1,
          0,
          -53.5
        ],
        [
          71,
          0,
          -62
        ]
      ]
    },
    {
      "id": "way/311545261",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          129,
          0,
          -110.8
        ],
        [
          106.7,
          0,
          -124.7
        ]
      ]
    },
    {
      "id": "way/313804277",
      "class": "service",
      "width": 3,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          69.4,
          0,
          57.7
        ],
        [
          66,
          0,
          62.9
        ]
      ]
    },
    {
      "id": "way/356521800",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          92.9,
          0,
          -44.1
        ],
        [
          85.2,
          0,
          -48.5
        ]
      ]
    },
    {
      "id": "way/356521810",
      "class": "steps",
      "width": 5,
      "surface": "concrete",
      "name": null,
      "points": [
        [
          84.6,
          0,
          -23.6
        ],
        [
          82,
          0,
          -25
        ]
      ]
    },
    {
      "id": "way/606469001",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          103.7,
          0,
          -35.2
        ],
        [
          102.1,
          0,
          -35.3
        ]
      ]
    },
    {
      "id": "way/606469002",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          103.8,
          0,
          -37.9
        ],
        [
          102.3,
          0,
          -38.7
        ]
      ]
    },
    {
      "id": "way/606469003",
      "class": "steps",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          105.1,
          0,
          -39.5
        ],
        [
          104.3,
          0,
          -40.9
        ]
      ]
    },
    {
      "id": "way/606469004",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          99.4,
          0,
          -40.3
        ],
        [
          101.9,
          0,
          -44.5
        ],
        [
          104.3,
          0,
          -40.9
        ]
      ]
    },
    {
      "id": "way/606469005",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          102.3,
          0,
          -38.7
        ],
        [
          99.4,
          0,
          -40.3
        ]
      ]
    },
    {
      "id": "way/606469006",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          102.1,
          0,
          -35.3
        ],
        [
          96.7,
          0,
          -35.7
        ]
      ]
    },
    {
      "id": "way/823823700",
      "class": "steps",
      "width": 5,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          -2.7,
          0,
          -43.5
        ],
        [
          5.6,
          0,
          -39.4
        ]
      ]
    },
    {
      "id": "way/1105843486",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          19.9,
          0,
          -38.5
        ],
        [
          18.9,
          0,
          -40.8
        ],
        [
          12.2,
          0,
          -49.1
        ],
        [
          10.5,
          0,
          -50.1
        ]
      ]
    },
    {
      "id": "way/1204313764",
      "class": "service",
      "width": 3,
      "surface": null,
      "name": null,
      "points": [
        [
          42.9,
          0,
          99.7
        ],
        [
          34.9,
          0,
          110.2
        ]
      ]
    },
    {
      "id": "way/1217525798",
      "class": "footway",
      "width": 2,
      "surface": "sett",
      "name": null,
      "points": [
        [
          85.1,
          0,
          -18.2
        ],
        [
          87.4,
          0,
          -22
        ],
        [
          84.6,
          0,
          -23.6
        ]
      ]
    },
    {
      "id": "way/1217525799",
      "class": "steps",
      "width": 5,
      "surface": "sett",
      "name": null,
      "points": [
        [
          84.1,
          0,
          -16.7
        ],
        [
          85.1,
          0,
          -18.2
        ]
      ]
    },
    {
      "id": "way/1305881606",
      "class": "residential",
      "width": 9,
      "surface": "sett",
      "name": "Poļu gāte",
      "points": [
        [
          43.6,
          0,
          -15.4
        ],
        [
          59.9,
          0,
          -6.2
        ]
      ]
    },
    {
      "id": "way/1335913903",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          27.1,
          0,
          68.6
        ],
        [
          37.9,
          0,
          52.5
        ],
        [
          37.8,
          0,
          51.1
        ]
      ]
    },
    {
      "id": "way/1335913904",
      "class": "path",
      "width": 1.5,
      "surface": null,
      "name": null,
      "points": [
        [
          7.9,
          0,
          77.8
        ],
        [
          0.8,
          0,
          77.5
        ],
        [
          -3.4,
          0,
          79.7
        ],
        [
          -5.2,
          0,
          78.7
        ]
      ]
    },
    {
      "id": "way/1335913908",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          -5.2,
          0,
          78.7
        ],
        [
          -11.9,
          0,
          85.5
        ],
        [
          -15,
          0,
          90.3
        ]
      ]
    },
    {
      "id": "way/1346606605",
      "class": "proposed",
      "width": 5,
      "surface": null,
      "name": null,
      "points": [
        [
          -78.4,
          0,
          166.5
        ],
        [
          -67.6,
          0,
          134.7
        ],
        [
          -57.5,
          0,
          115.4
        ],
        [
          -50.8,
          0,
          96.7
        ],
        [
          -43.4,
          0,
          79.7
        ],
        [
          -8.1,
          0,
          16.2
        ],
        [
          165,
          0,
          -286.6
        ],
        [
          179.9,
          0,
          -313.7
        ],
        [
          197.7,
          0,
          -349.6
        ],
        [
          226.6,
          0,
          -386.1
        ],
        [
          241.9,
          0,
          -404.1
        ],
        [
          287.5,
          0,
          -454.6
        ],
        [
          311.7,
          0,
          -479.3
        ],
        [
          331.7,
          0,
          -498.1
        ],
        [
          350.8,
          0,
          -514.8
        ],
        [
          369.7,
          0,
          -533.9
        ],
        [
          386.8,
          0,
          -547.5
        ],
        [
          418.5,
          0,
          -576.1
        ],
        [
          433.7,
          0,
          -595.3
        ],
        [
          441.2,
          0,
          -602.3
        ],
        [
          477.6,
          0,
          -634.7
        ],
        [
          503.8,
          0,
          -656.5
        ],
        [
          526.2,
          0,
          -669.8
        ],
        [
          543.7,
          0,
          -681.6
        ],
        [
          565.3,
          0,
          -693.4
        ],
        [
          568.9,
          0,
          -697.8
        ],
        [
          571.7,
          0,
          -703.1
        ],
        [
          579.6,
          0,
          -709.4
        ]
      ]
    },
    {
      "id": "way/1355001623",
      "class": "footway",
      "width": 2,
      "surface": "asphalt",
      "name": null,
      "points": [
        [
          170.9,
          0,
          -179.6
        ],
        [
          120.4,
          0,
          -96.7
        ],
        [
          67.9,
          0,
          -7
        ],
        [
          64.4,
          0,
          -3.7
        ]
      ]
    },
    {
      "id": "way/1355001627",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          153.9,
          0,
          -176
        ],
        [
          119.3,
          0,
          -117
        ],
        [
          115,
          0,
          -113.4
        ],
        [
          105.2,
          0,
          -97.5
        ],
        [
          103,
          0,
          -90.4
        ],
        [
          59,
          0,
          -15.1
        ],
        [
          56.3,
          0,
          -15
        ],
        [
          47.3,
          0,
          -20.6
        ]
      ]
    },
    {
      "id": "way/1355001628",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          61.8,
          0,
          0.8
        ],
        [
          111.7,
          0,
          26.2
        ],
        [
          114.9,
          0,
          28.6
        ],
        [
          116.6,
          0,
          31.5
        ],
        [
          116.6,
          0,
          36.4
        ],
        [
          115.3,
          0,
          39.8
        ],
        [
          101.3,
          0,
          68.3
        ]
      ]
    },
    {
      "id": "way/1355001629",
      "class": "footway",
      "width": 2,
      "surface": "unhewn_cobblestone",
      "name": null,
      "points": [
        [
          -6.3,
          0,
          71.9
        ],
        [
          7.1,
          0,
          73.9
        ],
        [
          32.2,
          0,
          36.7
        ]
      ]
    },
    {
      "id": "way/1355001630",
      "class": "service",
      "width": 3,
      "surface": null,
      "name": null,
      "points": [
        [
          86.2,
          0,
          64.4
        ],
        [
          86.5,
          0,
          62
        ],
        [
          91.1,
          0,
          51.1
        ],
        [
          69.3,
          0,
          39.7
        ],
        [
          68.2,
          0,
          34.8
        ],
        [
          61.3,
          0,
          31.6
        ],
        [
          61.5,
          0,
          27.9
        ],
        [
          65.3,
          0,
          20.8
        ]
      ]
    },
    {
      "id": "way/1355001631",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          116.8,
          0,
          93.8
        ],
        [
          119.8,
          0,
          79.9
        ]
      ]
    },
    {
      "id": "way/1425644287",
      "class": "pedestrian",
      "width": 4,
      "surface": "sett",
      "name": "Daugavas gāte",
      "points": [
        [
          110.6,
          0,
          77.8
        ],
        [
          102.7,
          0,
          69
        ],
        [
          94.7,
          0,
          65
        ]
      ]
    },
    {
      "id": "way/1426630612",
      "class": "footway",
      "width": 2,
      "surface": "paving_stones",
      "name": null,
      "points": [
        [
          101.3,
          0,
          68.3
        ],
        [
          99.8,
          0,
          70.9
        ],
        [
          101.9,
          0,
          76.6
        ],
        [
          101.3,
          0,
          79.8
        ],
        [
          96.8,
          0,
          89.1
        ],
        [
          -10,
          0,
          292.1
        ],
        [
          -16.1,
          0,
          294.9
        ],
        [
          -54.2,
          0,
          282.1
        ],
        [
          -56.4,
          0,
          278.1
        ],
        [
          -49,
          0,
          250.8
        ]
      ]
    },
    {
      "id": "way/1500883463",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          -16.6,
          0,
          119.3
        ],
        [
          -13.3,
          0,
          120.3
        ]
      ]
    },
    {
      "id": "way/1500883464",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          -23.4,
          0,
          117.3
        ],
        [
          -16.6,
          0,
          119.3
        ]
      ]
    },
    {
      "id": "way/1501212205",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          59,
          0,
          -15.1
        ],
        [
          69.2,
          0,
          -9.3
        ]
      ]
    },
    {
      "id": "way/1501212206",
      "class": "footway",
      "width": 2,
      "surface": null,
      "name": null,
      "points": [
        [
          116.6,
          0,
          31.5
        ],
        [
          125.5,
          0,
          31.8
        ]
      ]
    }
  ],
  "buildings": [
    {
      "id": "way/87493931",
      "kind": "residential",
      "height": 12,
      "levels": 4,
      "name": "9",
      "footprint": [
        [
          106.4,
          -68
        ],
        [
          105.2,
          -66.1
        ],
        [
          105.9,
          -63.1
        ],
        [
          123,
          -50.3
        ],
        [
          128.7,
          -58.6
        ],
        [
          120,
          -65.2
        ],
        [
          124.2,
          -70.2
        ],
        [
          124.4,
          -72.8
        ],
        [
          133.6,
          -65.3
        ],
        [
          140.6,
          -73.8
        ],
        [
          122.3,
          -89.3
        ],
        [
          119.3,
          -89.4
        ],
        [
          117.7,
          -86.8
        ]
      ]
    },
    {
      "id": "way/87493950",
      "kind": "church",
      "height": 22,
      "levels": null,
      "name": "Rīgas Sāpju Dievmātes baznīca",
      "footprint": [
        [
          81.1,
          12.3
        ],
        [
          80.2,
          11.4
        ],
        [
          78,
          16
        ],
        [
          70.2,
          14.1
        ],
        [
          68.4,
          18
        ],
        [
          74.7,
          22.7
        ],
        [
          72.6,
          27.3
        ],
        [
          86.7,
          34.1
        ],
        [
          83.6,
          40.7
        ],
        [
          84.9,
          45.1
        ],
        [
          89,
          47.2
        ],
        [
          93.3,
          45.6
        ],
        [
          96.5,
          38.8
        ],
        [
          105.6,
          43.3
        ],
        [
          106.2,
          42
        ],
        [
          109.6,
          42.6
        ],
        [
          111,
          39.8
        ],
        [
          112.5,
          40.6
        ],
        [
          115.4,
          31.4
        ],
        [
          112.1,
          27.4
        ]
      ]
    },
    {
      "id": "way/87494024",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": "5",
      "footprint": [
        [
          91,
          -9.1
        ],
        [
          113.6,
          5.7
        ],
        [
          122.5,
          -7.7
        ],
        [
          98.8,
          -22.3
        ]
      ]
    },
    {
      "id": "way/87494062",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": "5",
      "footprint": [
        [
          90.9,
          60.1
        ],
        [
          101.8,
          65.4
        ],
        [
          110.2,
          48.3
        ],
        [
          99.3,
          43
        ]
      ]
    },
    {
      "id": "way/135466072",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": "3",
      "footprint": [
        [
          122.5,
          -7.7
        ],
        [
          131.4,
          -1.8
        ],
        [
          125.8,
          8.3
        ],
        [
          115.8,
          2.2
        ]
      ]
    },
    {
      "id": "way/135466073",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": null,
      "footprint": [
        [
          84.7,
          1.5
        ],
        [
          91,
          -9.1
        ],
        [
          98.8,
          -3.3
        ],
        [
          95.6,
          1.5
        ],
        [
          100.5,
          4.5
        ],
        [
          97.8,
          9.4
        ]
      ]
    },
    {
      "id": "way/135466074",
      "kind": "residential",
      "height": 9,
      "levels": 3,
      "name": "7",
      "footprint": [
        [
          136.7,
          20.5
        ],
        [
          124.5,
          25.6
        ],
        [
          102.8,
          13
        ],
        [
          109.1,
          2.9
        ],
        [
          119.1,
          8.7
        ],
        [
          116.7,
          12.5
        ],
        [
          120.9,
          15.1
        ],
        [
          122.8,
          10
        ],
        [
          126.9,
          11.4
        ],
        [
          127.7,
          14.1
        ],
        [
          131.4,
          13
        ]
      ]
    },
    {
      "id": "way/135466075",
      "kind": "residential",
      "height": 9,
      "levels": 3,
      "name": "9",
      "footprint": [
        [
          131.4,
          13
        ],
        [
          129.9,
          9.7
        ],
        [
          126.4,
          7.3
        ],
        [
          131.4,
          -1.8
        ],
        [
          136.2,
          1.9
        ],
        [
          146,
          16.4
        ],
        [
          136.7,
          20.5
        ]
      ]
    },
    {
      "id": "way/135466089",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": "5",
      "footprint": [
        [
          98.8,
          -22.3
        ],
        [
          94,
          -25.1
        ],
        [
          86.4,
          -12.1
        ],
        [
          91,
          -9.1
        ]
      ]
    },
    {
      "id": "way/135466096",
      "kind": "residential",
      "height": 6,
      "levels": 2,
      "name": "17",
      "footprint": [
        [
          140.6,
          -73.8
        ],
        [
          151.4,
          -64.8
        ],
        [
          132.8,
          -39.3
        ],
        [
          120.6,
          -46.9
        ],
        [
          133.6,
          -65.3
        ]
      ]
    },
    {
      "id": "way/169689422",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": null,
      "footprint": [
        [
          40,
          47.3
        ],
        [
          38.5,
          49.8
        ],
        [
          40.5,
          51.1
        ],
        [
          42,
          48.6
        ]
      ]
    },
    {
      "id": "way/171926518",
      "kind": "church",
      "height": 22,
      "levels": null,
      "name": "Anglikāņu baznīca",
      "footprint": [
        [
          103.6,
          -32.8
        ],
        [
          103.8,
          -37.9
        ],
        [
          109.4,
          -43
        ],
        [
          135.7,
          -28.1
        ],
        [
          127.8,
          -14.6
        ],
        [
          102.5,
          -29.8
        ],
        [
          104.2,
          -32.4
        ]
      ]
    },
    {
      "id": "way/1217525797",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": null,
      "footprint": [
        [
          86.1,
          -11.4
        ],
        [
          84.4,
          -8.6
        ],
        [
          86.6,
          -7.2
        ],
        [
          88.3,
          -10.1
        ]
      ]
    },
    {
      "id": "way/1335913907",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": "3",
      "footprint": [
        [
          -3.5,
          75.3
        ],
        [
          -5.3,
          77.6
        ],
        [
          -4,
          78.7
        ],
        [
          -2.1,
          76.3
        ]
      ]
    },
    {
      "id": "way/1499247201",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": null,
      "footprint": [
        [
          55,
          27.7
        ],
        [
          57.5,
          29.3
        ],
        [
          70.8,
          7.8
        ],
        [
          68.1,
          6.1
        ]
      ]
    },
    {
      "id": "way/1499247204",
      "kind": "yes",
      "height": 3,
      "levels": 1,
      "name": null,
      "footprint": [
        [
          72,
          30.6
        ],
        [
          71.1,
          32.3
        ],
        [
          64.3,
          29.2
        ],
        [
          68.8,
          19.1
        ],
        [
          74.7,
          22.7
        ],
        [
          73.2,
          27.5
        ]
      ]
    },
    {
      "id": "way/1499247205",
      "kind": "yes",
      "height": 3,
      "levels": 1,
      "name": null,
      "footprint": [
        [
          77.1,
          33.1
        ],
        [
          72,
          30.6
        ],
        [
          73.2,
          27.5
        ],
        [
          78.6,
          30.1
        ]
      ]
    },
    {
      "id": "way/1499247206",
      "kind": "yes",
      "height": 3,
      "levels": 1,
      "name": null,
      "footprint": [
        [
          78.6,
          30.1
        ],
        [
          75.9,
          35.7
        ],
        [
          84,
          39.6
        ],
        [
          86.7,
          34.1
        ]
      ]
    },
    {
      "id": "way/1499247207",
      "kind": "yes",
      "height": 9,
      "levels": null,
      "name": null,
      "footprint": [
        [
          46,
          41.9
        ],
        [
          52.5,
          31.3
        ],
        [
          64.3,
          37
        ],
        [
          62.7,
          40.5
        ],
        [
          63.6,
          43.6
        ],
        [
          74.2,
          48.3
        ],
        [
          74.9,
          46.8
        ],
        [
          82.3,
          50.5
        ],
        [
          81.7,
          51.8
        ],
        [
          87.6,
          55.5
        ],
        [
          86.3,
          57.8
        ],
        [
          84.2,
          56.7
        ],
        [
          82.5,
          60
        ],
        [
          58.8,
          48.1
        ]
      ]
    },
    {
      "id": "relation/1297991",
      "kind": "apartments",
      "height": 15,
      "levels": 5,
      "name": "14",
      "footprint": [
        [
          176.8,
          -113.4
        ],
        [
          167.8,
          -120.9
        ],
        [
          165.5,
          -118.8
        ],
        [
          164.2,
          -119.8
        ],
        [
          166.2,
          -122.4
        ],
        [
          159,
          -128.2
        ],
        [
          157.2,
          -125.9
        ],
        [
          155.2,
          -127.3
        ],
        [
          156.5,
          -129.6
        ],
        [
          146.9,
          -135.6
        ],
        [
          126.5,
          -101.6
        ],
        [
          127.2,
          -98.1
        ],
        [
          144.2,
          -84.1
        ],
        [
          147.2,
          -84.2
        ],
        [
          162,
          -98.8
        ]
      ]
    },
    {
      "id": "relation/1393926",
      "kind": "castle",
      "height": 9,
      "levels": null,
      "name": "Rīgas Pils",
      "footprint": [
        [
          14.9,
          90.5
        ],
        [
          16.3,
          92
        ],
        [
          41.8,
          52.8
        ],
        [
          40.7,
          52.1
        ],
        [
          43.3,
          47.8
        ],
        [
          47.8,
          50.5
        ],
        [
          47.2,
          51.5
        ],
        [
          85.9,
          74.6
        ],
        [
          87.1,
          72
        ],
        [
          91.8,
          69
        ],
        [
          96.9,
          69.7
        ],
        [
          100.2,
          73.2
        ],
        [
          100.6,
          78.8
        ],
        [
          58.2,
          159.5
        ],
        [
          51.5,
          156.6
        ],
        [
          50.1,
          159.8
        ],
        [
          56.2,
          162.6
        ],
        [
          48.8,
          178.1
        ],
        [
          27.4,
          167.1
        ],
        [
          31.5,
          159.4
        ],
        [
          42.8,
          163.8
        ],
        [
          48.2,
          155.2
        ],
        [
          22,
          143.7
        ],
        [
          18.9,
          151.7
        ],
        [
          10.5,
          148.1
        ],
        [
          13.7,
          138.9
        ],
        [
          6.3,
          135.2
        ],
        [
          6.9,
          134
        ],
        [
          -14.8,
          125.3
        ],
        [
          -4.5,
          91.4
        ],
        [
          -5.9,
          91
        ],
        [
          -4.5,
          86.1
        ],
        [
          7.2,
          89.4
        ],
        [
          13.1,
          89.5
        ]
      ]
    }
  ],
  "water": [
    {
      "id": "way/69885572",
      "kind": "river",
      "polygons": [
        [
          [
            10440.7,
            -10898.5
          ],
          [
            9833.2,
            -10245.9
          ],
          [
            9555.7,
            -9851.3
          ],
          [
            9471,
            -9631.8
          ],
          [
            9094,
            -9206.5
          ],
          [
            8803,
            -8979.7
          ],
          [
            7746.7,
            -8357.4
          ],
          [
            6909.3,
            -7964.8
          ],
          [
            6223.8,
            -7458.8
          ],
          [
            5711.3,
            -6591.8
          ],
          [
            5315,
            -5744.2
          ],
          [
            4152.7,
            -4555.1
          ],
          [
            3144.1,
            -3295.6
          ],
          [
            1102.5,
            -1326.7
          ],
          [
            198,
            -738.8
          ],
          [
            100.4,
            -593.6
          ],
          [
            -262.9,
            28.5
          ],
          [
            -422.7,
            534.8
          ],
          [
            -625.2,
            1314.8
          ],
          [
            -761.7,
            1948.3
          ],
          [
            -727.4,
            2458.7
          ],
          [
            -700,
            2905.5
          ],
          [
            -512.9,
            4410.9
          ],
          [
            -509.7,
            5592.3
          ],
          [
            -513.9,
            6706.8
          ],
          [
            -639.9,
            8174.3
          ],
          [
            -909.8,
            8875.1
          ],
          [
            -996.9,
            9019
          ],
          [
            -2120.7,
            10365.7
          ],
          [
            -2637.2,
            10879.5
          ],
          [
            -3535.4,
            11637.4
          ],
          [
            -4557.7,
            12479.9
          ]
        ]
      ]
    },
    {
      "id": "way/84914188",
      "kind": "river",
      "polygons": [
        [
          [
            -438.6,
            2939.1
          ],
          [
            -236.2,
            2354.2
          ],
          [
            -236.3,
            2334.6
          ],
          [
            -233.8,
            2321.1
          ],
          [
            -235.1,
            2311.3
          ],
          [
            -236.3,
            2310.1
          ],
          [
            -266.9,
            2306.4
          ],
          [
            -266.9,
            2301.5
          ],
          [
            -236.3,
            2303.9
          ],
          [
            -236.3,
            2300.3
          ],
          [
            -235.1,
            2300.3
          ],
          [
            -233.9,
            2290.5
          ],
          [
            -235.2,
            2216.9
          ],
          [
            -236.4,
            2216.9
          ],
          [
            -236.4,
            2214.5
          ],
          [
            -235.2,
            2214.5
          ],
          [
            -236.5,
            2142.2
          ],
          [
            -237.8,
            2136
          ],
          [
            -236.9,
            2077.5
          ],
          [
            -300.9,
            2076.7
          ],
          [
            -416.1,
            2393.7
          ],
          [
            -447.9,
            2424.3
          ],
          [
            -469.8,
            2493
          ],
          [
            -454.9,
            2663.3
          ],
          [
            -464.7,
            2664.6
          ],
          [
            -480.8,
            2499.1
          ],
          [
            -479.6,
            2490.6
          ],
          [
            -446.7,
            2388.8
          ],
          [
            -450.4,
            2383.9
          ],
          [
            -451.6,
            2379
          ],
          [
            -449.2,
            2358.2
          ],
          [
            -465.2,
            2299.3
          ],
          [
            -470.1,
            2284.7
          ],
          [
            -472.5,
            2284.5
          ],
          [
            -473,
            2281.5
          ],
          [
            -470.1,
            2281
          ],
          [
            -498.4,
            2164.6
          ],
          [
            -521.8,
            2048.2
          ],
          [
            -525.5,
            2044.5
          ],
          [
            -531.6,
            2022.5
          ],
          [
            -532.9,
            2011.4
          ],
          [
            -531.6,
            2005.3
          ],
          [
            -528,
            1999.2
          ],
          [
            -530.5,
            1974.7
          ],
          [
            -529.3,
            1972.2
          ],
          [
            -532.9,
            1951.4
          ],
          [
            -534.2,
            1934.2
          ],
          [
            -533,
            1929.3
          ],
          [
            -540.4,
            1842.3
          ],
          [
            -539.2,
            1823.9
          ],
          [
            -541.7,
            1819
          ],
          [
            -555.2,
            1820.3
          ],
          [
            -555.2,
            1815.4
          ],
          [
            -553.9,
            1815.4
          ],
          [
            -554,
            1749.2
          ],
          [
            -555.2,
            1749.2
          ],
          [
            -556.5,
            1741.8
          ],
          [
            -547.9,
            1743
          ],
          [
            -549.2,
            1727.1
          ],
          [
            -556.5,
            1725.9
          ],
          [
            -556.5,
            1721
          ],
          [
            -547.9,
            1721
          ],
          [
            -549.2,
            1681.8
          ],
          [
            -556.6,
            1681.8
          ],
          [
            -556.6,
            1676.9
          ],
          [
            -550.4,
            1676.9
          ],
          [
            -540.7,
            1664.7
          ],
          [
            -546.6,
            1661.1
          ],
          [
            -500,
            1426.9
          ],
          [
            -488.1,
            1429.9
          ],
          [
            -484.7,
            1418.2
          ],
          [
            -487.2,
            1417
          ],
          [
            -478.6,
            1386.3
          ],
          [
            -440.5,
            1183.6
          ],
          [
            -429.4,
            1154.8
          ],
          [
            -411.8,
            1161.3
          ],
          [
            -359.2,
            1029.5
          ],
          [
            -277,
            809.5
          ],
          [
            -260.4,
            752.8
          ],
          [
            -283.6,
            744.8
          ],
          [
            -287,
            740.2
          ],
          [
            -273.2,
            690.6
          ],
          [
            -269.9,
            689.2
          ],
          [
            -252.5,
            693.3
          ],
          [
            -134.2,
            248.5
          ],
          [
            -128.4,
            244.8
          ],
          [
            -120.8,
            225.1
          ],
          [
            -112.1,
            225.5
          ],
          [
            -85.3,
            158.9
          ],
          [
            -68.8,
            109.3
          ],
          [
            -25.8,
            7.5
          ],
          [
            -2.7,
            -43.5
          ],
          [
            31.4,
            -108.3
          ],
          [
            100.4,
            -224.3
          ],
          [
            177.6,
            -343.9
          ],
          [
            200.4,
            -373.6
          ],
          [
            244.2,
            -422.9
          ],
          [
            240.5,
            -427.8
          ],
          [
            260.1,
            -449.5
          ],
          [
            -103.8,
            -778
          ],
          [
            -118.9,
            -750.9
          ],
          [
            -121.5,
            -750.8
          ],
          [
            -124.4,
            -747.9
          ],
          [
            -207.1,
            -562.7
          ],
          [
            -412,
            -196.2
          ],
          [
            -431.4,
            -163.9
          ],
          [
            -435.9,
            -162.1
          ],
          [
            -495.5,
            -78.7
          ],
          [
            -483,
            -54.7
          ],
          [
            -548.1,
            138.9
          ],
          [
            -554.9,
            136.6
          ],
          [
            -559.4,
            151.6
          ],
          [
            -578.2,
            191.8
          ],
          [
            -596.7,
            204.7
          ],
          [
            -659.3,
            210.8
          ],
          [
            -702,
            199
          ],
          [
            -748,
            171.7
          ],
          [
            -770.1,
            123.9
          ],
          [
            -776.4,
            103.1
          ],
          [
            -777.5,
            87.1
          ],
          [
            -780.1,
            81.5
          ],
          [
            -785,
            90
          ],
          [
            -793.4,
            150.1
          ],
          [
            -795.8,
            190.6
          ],
          [
            -803.1,
            238.4
          ],
          [
            -811.6,
            319.3
          ],
          [
            -840.4,
            395.6
          ],
          [
            -848.1,
            423.5
          ],
          [
            -861.2,
            737.3
          ],
          [
            -861.1,
            796.1
          ],
          [
            -864.8,
            816.9
          ],
          [
            -874.1,
            836.9
          ],
          [
            -882.1,
            849.5
          ],
          [
            -943.2,
            983.8
          ],
          [
            -954.8,
            1012.3
          ],
          [
            -981.9,
            1094
          ],
          [
            -989.2,
            1111.2
          ],
          [
            -1006.1,
            1171.5
          ],
          [
            -1045.9,
            1362.3
          ],
          [
            -1059.3,
            1539
          ],
          [
            -1068.7,
            1700.5
          ],
          [
            -1067.1,
            1702.7
          ],
          [
            -1070.9,
            1705.5
          ],
          [
            -1071.5,
            1717.1
          ],
          [
            -1068.7,
            1718.7
          ],
          [
            -1070.9,
            1763.2
          ],
          [
            -1073,
            1768.5
          ],
          [
            -1075.4,
            1820.2
          ],
          [
            -1081.9,
            1831.1
          ],
          [
            -1074.2,
            1834.4
          ],
          [
            -1072.6,
            1991.3
          ],
          [
            -1066.3,
            2079.5
          ],
          [
            -1059,
            2153.5
          ],
          [
            -1056.4,
            2153.9
          ],
          [
            -1055.2,
            2167.7
          ],
          [
            -1057.4,
            2172.8
          ],
          [
            -1043.5,
            2426
          ],
          [
            -991.2,
            2482.8
          ],
          [
            -973.4,
            2510
          ],
          [
            -963.5,
            2533.5
          ],
          [
            -835.8,
            3018.5
          ],
          [
            -838.8,
            3027.8
          ],
          [
            -838.4,
            3033.4
          ],
          [
            -829.4,
            3056.3
          ],
          [
            -825.6,
            3084.2
          ],
          [
            -824.2,
            3128.9
          ],
          [
            -818.6,
            3165.5
          ],
          [
            -822.5,
            3322
          ],
          [
            -827.3,
            3337.9
          ],
          [
            -827.3,
            3352.6
          ],
          [
            -823.6,
            3358.7
          ],
          [
            -827.3,
            3386.9
          ],
          [
            -832.2,
            3394.3
          ],
          [
            -835.4,
            3405.3
          ],
          [
            -836.6,
            3416.5
          ],
          [
            -842.3,
            3429.1
          ],
          [
            -849.9,
            3455.5
          ],
          [
            -849.3,
            3458.1
          ],
          [
            -846.5,
            3458.1
          ],
          [
            -843.1,
            3462
          ],
          [
            -838.8,
            3473.4
          ],
          [
            -841.6,
            3497.1
          ],
          [
            -857.2,
            3521.2
          ],
          [
            -858.9,
            3527.7
          ],
          [
            -859.6,
            3551.8
          ],
          [
            -863.1,
            3560.4
          ],
          [
            -865.5,
            3578.2
          ],
          [
            -869.7,
            3593.8
          ],
          [
            -866.2,
            3617
          ],
          [
            -866.2,
            3631.8
          ],
          [
            -859.2,
            3645.6
          ],
          [
            -848.5,
            3657
          ],
          [
            -848,
            3662
          ],
          [
            -859.8,
            3673.9
          ],
          [
            -863.2,
            3679.9
          ],
          [
            -866.3,
            3703.9
          ],
          [
            -873.6,
            3724.8
          ],
          [
            -875.1,
            3734
          ],
          [
            -874.8,
            3750.3
          ],
          [
            -868.8,
            3769.1
          ],
          [
            -859.7,
            3786
          ],
          [
            -849.9,
            3800.1
          ],
          [
            -842.2,
            3818.9
          ],
          [
            -833.6,
            3831.1
          ],
          [
            -845.6,
            3857.3
          ],
          [
            -845.9,
            3894.4
          ],
          [
            -840.7,
            3922.7
          ],
          [
            -821.6,
            3981.3
          ],
          [
            -818,
            3986.2
          ],
          [
            -809.4,
            3987.4
          ],
          [
            -806.9,
            3989.9
          ],
          [
            -806.9,
            3992.3
          ],
          [
            -822.8,
            3998.5
          ],
          [
            -822.8,
            4002.2
          ],
          [
            -828.9,
            4014.4
          ],
          [
            -833.8,
            4016.9
          ],
          [
            -844.8,
            4029.1
          ],
          [
            -844.8,
            4045.1
          ],
          [
            -846,
            4050
          ],
          [
            -849.7,
            4054.9
          ],
          [
            -852.1,
            4065.9
          ],
          [
            -850,
            4075
          ],
          [
            -846.2,
            4145.7
          ],
          [
            -842.6,
            4150.6
          ],
          [
            -833.9,
            4152.4
          ],
          [
            -824.2,
            4158.4
          ],
          [
            -816.2,
            4167.9
          ],
          [
            -815.2,
            4175.2
          ],
          [
            -818.7,
            4180.3
          ],
          [
            -825.1,
            4184.8
          ],
          [
            -827.5,
            4190.9
          ],
          [
            -820.1,
            4247.3
          ],
          [
            -206.7,
            4228.1
          ],
          [
            -23.3,
            3931.9
          ],
          [
            -77.9,
            3548.9
          ],
          [
            -181.9,
            3556.4
          ],
          [
            -159.5,
            3850.5
          ],
          [
            -188.8,
            3854.2
          ],
          [
            -262.2,
            3940.1
          ],
          [
            -346.6,
            3947.6
          ],
          [
            -346.6,
            3948.8
          ],
          [
            -362.5,
            3951.3
          ],
          [
            -363.8,
            3950.1
          ],
          [
            -365,
            3936.6
          ],
          [
            -371.1,
            3936.6
          ],
          [
            -399.8,
            3556.7
          ],
          [
            -402.3,
            3516.3
          ],
          [
            -396.2,
            3515
          ],
          [
            -431.1,
            3033.4
          ]
        ]
      ]
    }
  ],
  "landuse": [
    {
      "id": "way/45018608",
      "kind": "park",
      "polygons": [
        [
          [
            106.2,
            94.6
          ],
          [
            111.6,
            90.2
          ],
          [
            117.3,
            90
          ],
          [
            136.7,
            95.9
          ],
          [
            138.7,
            104.5
          ],
          [
            143.1,
            182.8
          ],
          [
            137.2,
            189.9
          ],
          [
            80.9,
            175.3
          ],
          [
            74.4,
            163.2
          ]
        ]
      ]
    },
    {
      "id": "way/85390121",
      "kind": "grass",
      "polygons": [
        [
          [
            110.7,
            -126.4
          ],
          [
            140.2,
            -179
          ],
          [
            145.6,
            -184.5
          ],
          [
            151.8,
            -178.3
          ],
          [
            118.3,
            -121.9
          ]
        ]
      ]
    },
    {
      "id": "way/85390128",
      "kind": "grass",
      "polygons": [
        [
          [
            43,
            -9.1
          ],
          [
            60.2,
            0.7
          ],
          [
            39.6,
            35.2
          ],
          [
            36.8,
            37
          ],
          [
            21,
            27.7
          ],
          [
            42.1,
            -8.2
          ]
        ]
      ]
    },
    {
      "id": "way/85390132",
      "kind": "grass",
      "polygons": [
        [
          [
            19.3,
            31.2
          ],
          [
            36.8,
            41.7
          ],
          [
            35.8,
            42.8
          ],
          [
            32,
            40.5
          ],
          [
            8.2,
            76.5
          ],
          [
            -4.9,
            74.2
          ]
        ]
      ]
    },
    {
      "id": "way/135466085",
      "kind": "park",
      "polygons": [
        [
          [
            10.5,
            148.1
          ],
          [
            1.4,
            144.9
          ],
          [
            -12.1,
            135
          ],
          [
            -11,
            133.7
          ],
          [
            -19.6,
            127.2
          ],
          [
            -6.4,
            82.4
          ],
          [
            10.3,
            84.2
          ],
          [
            8.2,
            76.5
          ],
          [
            -4.9,
            74.2
          ],
          [
            -17.5,
            91.9
          ],
          [
            -22.1,
            103.8
          ],
          [
            -25,
            117.7
          ],
          [
            -23.9,
            140.7
          ],
          [
            -12.5,
            145.6
          ],
          [
            -27,
            202.7
          ],
          [
            -24.8,
            204.7
          ],
          [
            24.4,
            221.4
          ],
          [
            48.8,
            178.1
          ],
          [
            27.4,
            167.1
          ],
          [
            31.5,
            159.4
          ],
          [
            14.9,
            150
          ]
        ]
      ]
    },
    {
      "id": "way/169683897",
      "kind": "grass",
      "polygons": [
        [
          [
            116,
            -205.1
          ],
          [
            94.9,
            -201.1
          ],
          [
            90.6,
            -194.3
          ],
          [
            92,
            -193.4
          ],
          [
            89.8,
            -189.9
          ],
          [
            88.2,
            -190.9
          ],
          [
            74.3,
            -169.1
          ],
          [
            75.7,
            -168.2
          ],
          [
            73.5,
            -164.7
          ],
          [
            72.1,
            -165.6
          ],
          [
            64,
            -151.3
          ],
          [
            65.5,
            -150.5
          ],
          [
            63.6,
            -147.1
          ],
          [
            62.1,
            -148
          ],
          [
            54,
            -133.7
          ],
          [
            55.4,
            -132.9
          ],
          [
            53.5,
            -129.4
          ],
          [
            52.1,
            -130.2
          ],
          [
            43.3,
            -114.8
          ],
          [
            44.8,
            -113.9
          ],
          [
            42.8,
            -110.4
          ],
          [
            41.3,
            -111.3
          ],
          [
            29,
            -88.6
          ],
          [
            30.5,
            -87.8
          ],
          [
            28.6,
            -84.3
          ],
          [
            27.1,
            -85.2
          ],
          [
            20.7,
            -73.5
          ],
          [
            22.5,
            -72.5
          ],
          [
            20.8,
            -69.4
          ],
          [
            19.3,
            -70.2
          ],
          [
            11.4,
            -56.1
          ],
          [
            14.7,
            -54.2
          ],
          [
            12.9,
            -50.5
          ],
          [
            22.4,
            -40.5
          ],
          [
            30.7,
            -55.1
          ]
        ]
      ]
    },
    {
      "id": "way/169683898",
      "kind": "grass",
      "polygons": [
        [
          [
            -74.5,
            163.5
          ],
          [
            -79.3,
            161.7
          ],
          [
            -48.3,
            77.7
          ],
          [
            -39.9,
            57.5
          ],
          [
            -38.3,
            58.2
          ],
          [
            -36.8,
            55
          ],
          [
            -38.5,
            54
          ],
          [
            -30.8,
            36.8
          ],
          [
            -29.3,
            37.6
          ],
          [
            -27.9,
            34.3
          ],
          [
            -29.4,
            33.5
          ],
          [
            -20.5,
            12.2
          ],
          [
            -18.4,
            12.8
          ],
          [
            -16.9,
            9.7
          ],
          [
            -19,
            8.7
          ],
          [
            -13.6,
            -3.5
          ],
          [
            -11.8,
            -2.7
          ],
          [
            -10.3,
            -5.9
          ],
          [
            -12.1,
            -6.7
          ],
          [
            -4.8,
            -22.7
          ],
          [
            -1.4,
            -20.8
          ],
          [
            2.1,
            -28.1
          ],
          [
            7.2,
            -29.3
          ],
          [
            11.9,
            -26.8
          ],
          [
            11.2,
            -25.1
          ],
          [
            13.1,
            -23.9
          ],
          [
            -42.2,
            73
          ],
          [
            -50.7,
            90
          ],
          [
            -58.8,
            114.8
          ]
        ]
      ]
    },
    {
      "id": "way/169689463",
      "kind": "grass",
      "polygons": [
        [
          [
            3.6,
            118.9
          ],
          [
            5,
            113.4
          ],
          [
            2.9,
            111
          ],
          [
            1.1,
            111.4
          ],
          [
            0,
            117.4
          ]
        ]
      ]
    },
    {
      "id": "way/169689465",
      "kind": "grass",
      "polygons": [
        [
          [
            53.3,
            131
          ],
          [
            44.1,
            123.4
          ],
          [
            42.2,
            116.6
          ],
          [
            54.5,
            124
          ],
          [
            55.5,
            126.5
          ]
        ]
      ]
    },
    {
      "id": "way/169689467",
      "kind": "grass",
      "polygons": [
        [
          [
            -27.7,
            119.6
          ],
          [
            -29.2,
            181.3
          ],
          [
            -38.5,
            217.3
          ],
          [
            -48,
            222.7
          ]
        ]
      ]
    },
    {
      "id": "way/169689469",
      "kind": "grass",
      "polygons": [
        [
          [
            22.5,
            121.4
          ],
          [
            25.3,
            121.2
          ],
          [
            25.6,
            122.9
          ]
        ]
      ]
    },
    {
      "id": "way/169689470",
      "kind": "grass",
      "polygons": [
        [
          [
            26.9,
            123.6
          ],
          [
            29.1,
            122.7
          ],
          [
            30,
            125
          ]
        ]
      ]
    },
    {
      "id": "way/169689471",
      "kind": "grass",
      "polygons": [
        [
          [
            6.7,
            107.6
          ],
          [
            14.9,
            106.9
          ],
          [
            17.9,
            103.4
          ],
          [
            8.1,
            106.1
          ]
        ]
      ]
    },
    {
      "id": "way/169738898",
      "kind": "grass",
      "polygons": [
        [
          [
            82.5,
            60
          ],
          [
            84.2,
            60.8
          ],
          [
            85.7,
            57.5
          ],
          [
            84.2,
            56.7
          ]
        ]
      ]
    },
    {
      "id": "way/169738899",
      "kind": "grass",
      "polygons": [
        [
          [
            62.3,
            2.1
          ],
          [
            42.2,
            36.5
          ],
          [
            43.2,
            40.6
          ],
          [
            46,
            41.9
          ],
          [
            68,
            5.4
          ]
        ]
      ]
    },
    {
      "id": "way/477466586",
      "kind": "grass",
      "polygons": [
        [
          [
            106.9,
            -119.8
          ],
          [
            114.3,
            -115.2
          ],
          [
            104,
            -97.8
          ],
          [
            96.9,
            -102.4
          ]
        ]
      ]
    },
    {
      "id": "way/477466588",
      "kind": "grass",
      "polygons": [
        [
          [
            100.1,
            -91.1
          ],
          [
            57.8,
            -17.8
          ],
          [
            53.3,
            -17.7
          ],
          [
            50.8,
            -22.5
          ],
          [
            93.1,
            -95.8
          ]
        ]
      ]
    },
    {
      "id": "way/494679539",
      "kind": "residential",
      "polygons": [
        [
          [
            102.8,
            13
          ],
          [
            71.4,
            -6.8
          ],
          [
            85.5,
            -30.6
          ],
          [
            122.8,
            -8.2
          ],
          [
            136.2,
            1.9
          ],
          [
            146,
            16.4
          ],
          [
            124.5,
            25.6
          ]
        ]
      ]
    },
    {
      "id": "way/494679540",
      "kind": "residential",
      "polygons": [
        [
          [
            215,
            -5.4
          ],
          [
            214.4,
            -3.1
          ],
          [
            198.9,
            0.9
          ],
          [
            198.6,
            -0.2
          ],
          [
            167.8,
            9.4
          ],
          [
            164.4,
            8.3
          ],
          [
            137.7,
            -24.1
          ],
          [
            143.5,
            -33.4
          ],
          [
            120.6,
            -46.9
          ],
          [
            121.2,
            -47.8
          ],
          [
            103.3,
            -61.9
          ],
          [
            118.4,
            -88.5
          ],
          [
            122.3,
            -89.3
          ],
          [
            157.9,
            -59.6
          ],
          [
            201.2,
            -20.1
          ]
        ]
      ]
    },
    {
      "id": "way/494679545",
      "kind": "residential",
      "polygons": [
        [
          [
            144.2,
            -84.1
          ],
          [
            127.2,
            -98.1
          ],
          [
            126.5,
            -101.6
          ],
          [
            163.7,
            -164.1
          ],
          [
            179.2,
            -155
          ],
          [
            178.6,
            -154
          ],
          [
            196.3,
            -140.2
          ],
          [
            176.8,
            -113.4
          ],
          [
            147.2,
            -84.2
          ]
        ]
      ]
    },
    {
      "id": "way/1105843485",
      "kind": "grass",
      "polygons": [
        [
          [
            11.2,
            -47.1
          ],
          [
            8.2,
            -39.9
          ],
          [
            9.2,
            -35.4
          ],
          [
            14.4,
            -32.6
          ],
          [
            18.3,
            -39.4
          ]
        ]
      ]
    },
    {
      "id": "way/1322710420",
      "kind": "religious",
      "polygons": [
        [
          [
            132.8,
            -39.3
          ],
          [
            120.6,
            -46.9
          ],
          [
            121.2,
            -47.8
          ],
          [
            103.3,
            -61.9
          ],
          [
            89,
            -36.9
          ],
          [
            130.2,
            -11.9
          ],
          [
            143.5,
            -33.4
          ],
          [
            136.2,
            -37.7
          ]
        ]
      ]
    },
    {
      "id": "way/1360465840",
      "kind": "religious",
      "polygons": [
        [
          [
            79.9,
            12.1
          ],
          [
            68,
            5.4
          ],
          [
            46,
            41.9
          ],
          [
            82.5,
            60
          ],
          [
            84.2,
            56.7
          ],
          [
            101.8,
            65.4
          ],
          [
            110.2,
            48.3
          ],
          [
            104.5,
            45.6
          ],
          [
            106.2,
            42
          ],
          [
            108.2,
            43
          ],
          [
            111,
            39.8
          ],
          [
            112.5,
            40.6
          ],
          [
            115.2,
            35.2
          ],
          [
            113.8,
            34.5
          ],
          [
            114.9,
            30.1
          ],
          [
            112.2,
            27.2
          ],
          [
            80.2,
            11.4
          ]
        ]
      ]
    },
    {
      "id": "way/1444768717",
      "kind": "institutional",
      "polygons": [
        [
          [
            52.2,
            105.6
          ],
          [
            55.6,
            107.6
          ],
          [
            68.9,
            86
          ],
          [
            48.7,
            74.7
          ],
          [
            35.6,
            94.5
          ],
          [
            42.9,
            99.7
          ]
        ]
      ]
    },
    {
      "id": "way/1444768718",
      "kind": "institutional",
      "polygons": [
        [
          [
            0.9,
            105.3
          ],
          [
            -3.8,
            118.5
          ],
          [
            20.7,
            130
          ],
          [
            22.3,
            126.8
          ],
          [
            26.1,
            128.6
          ],
          [
            24.7,
            131.8
          ],
          [
            46.5,
            141.1
          ],
          [
            48.5,
            136.8
          ],
          [
            52.7,
            137.4
          ],
          [
            57.6,
            126.4
          ],
          [
            34.9,
            110.2
          ],
          [
            16.3,
            100.9
          ],
          [
            13,
            103.5
          ],
          [
            6.7,
            103.3
          ],
          [
            2.6,
            105.9
          ]
        ]
      ]
    },
    {
      "id": "way/1444768720",
      "kind": "institutional",
      "polygons": [
        [
          [
            41.5,
            46.6
          ],
          [
            32,
            40.5
          ],
          [
            8.2,
            76.5
          ],
          [
            10.3,
            84.2
          ],
          [
            -6.4,
            82.4
          ],
          [
            -19.6,
            127.2
          ],
          [
            -11,
            133.7
          ],
          [
            -12.1,
            135
          ],
          [
            1.4,
            144.9
          ],
          [
            10.5,
            148.1
          ],
          [
            14,
            136.7
          ],
          [
            -13.8,
            126
          ],
          [
            -15,
            124.1
          ],
          [
            -4.5,
            91.4
          ],
          [
            -5.9,
            91
          ],
          [
            -4.5,
            86.1
          ],
          [
            7.2,
            89.4
          ],
          [
            11.2,
            88.9
          ],
          [
            16.3,
            92
          ],
          [
            41.8,
            52.8
          ],
          [
            40.7,
            52.1
          ],
          [
            43.3,
            47.8
          ]
        ]
      ]
    }
  ],
  "trees": [
    {
      "id": "node/1808495991",
      "kind": "tree",
      "position": [
        53.8,
        0,
        -124.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808495992",
      "kind": "tree",
      "position": [
        117.9,
        0,
        -123.2
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808495993",
      "kind": "tree",
      "position": [
        114.7,
        0,
        -117.7
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808495994",
      "kind": "tree",
      "position": [
        50,
        0,
        -117.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496009",
      "kind": "tree",
      "position": [
        46.1,
        0,
        -110.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496018",
      "kind": "tree",
      "position": [
        43,
        0,
        -104.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496021",
      "kind": "tree",
      "position": [
        38.7,
        0,
        -97.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496023",
      "kind": "tree",
      "position": [
        98.6,
        0,
        -91
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496025",
      "kind": "tree",
      "position": [
        34.9,
        0,
        -90.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496032",
      "kind": "tree",
      "position": [
        95.7,
        0,
        -86
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496054",
      "kind": "tree",
      "position": [
        30.8,
        0,
        -82.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496055",
      "kind": "tree",
      "position": [
        92.5,
        0,
        -80.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496056",
      "kind": "tree",
      "position": [
        27.6,
        0,
        -76.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496057",
      "kind": "tree",
      "position": [
        89.4,
        0,
        -75.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496062",
      "kind": "tree",
      "position": [
        86.6,
        0,
        -70.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496067",
      "kind": "tree",
      "position": [
        83.9,
        0,
        -65.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496068",
      "kind": "tree",
      "position": [
        20.5,
        0,
        -62.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496069",
      "kind": "tree",
      "position": [
        80.4,
        0,
        -60.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496077",
      "kind": "tree",
      "position": [
        17.1,
        0,
        -55.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496078",
      "kind": "tree",
      "position": [
        77.8,
        0,
        -55.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496081",
      "kind": "tree",
      "position": [
        24.1,
        0,
        -52.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496083",
      "kind": "tree",
      "position": [
        74.6,
        0,
        -50.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496088",
      "kind": "tree",
      "position": [
        71.4,
        0,
        -45.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496089",
      "kind": "tree",
      "position": [
        20.2,
        0,
        -45.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496092",
      "kind": "tree",
      "position": [
        68.3,
        0,
        -40.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496096",
      "kind": "tree",
      "position": [
        65.5,
        0,
        -35
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496104",
      "kind": "tree",
      "position": [
        62.2,
        0,
        -29.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496112",
      "kind": "tree",
      "position": [
        59.7,
        0,
        -25.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496119",
      "kind": "tree",
      "position": [
        7.9,
        0,
        -21.7
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496122",
      "kind": "tree",
      "position": [
        56.4,
        0,
        -19.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496123",
      "kind": "tree",
      "position": [
        -1.2,
        0,
        -17.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496129",
      "kind": "tree",
      "position": [
        4.7,
        0,
        -15.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496131",
      "kind": "tree",
      "position": [
        -4.5,
        0,
        -10.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496136",
      "kind": "tree",
      "position": [
        -8,
        0,
        -3.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496138",
      "kind": "tree",
      "position": [
        50.7,
        0,
        -2.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496141",
      "kind": "tree",
      "position": [
        54,
        0,
        -1.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496143",
      "kind": "tree",
      "position": [
        57.5,
        0,
        0.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496144",
      "kind": "tree",
      "position": [
        -11.2,
        0,
        3.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496149",
      "kind": "tree",
      "position": [
        -14.3,
        0,
        10.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496154",
      "kind": "tree",
      "position": [
        -17.8,
        0,
        17.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496156",
      "kind": "tree",
      "position": [
        -20.9,
        0,
        24.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496157",
      "kind": "tree",
      "position": [
        47.7,
        0,
        30.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496158",
      "kind": "tree",
      "position": [
        29.8,
        0,
        30.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496160",
      "kind": "tree",
      "position": [
        -24.2,
        0,
        32.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496164",
      "kind": "tree",
      "position": [
        36.3,
        0,
        34.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496168",
      "kind": "tree",
      "position": [
        -28.6,
        0,
        41.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496169",
      "kind": "tree",
      "position": [
        -31.8,
        0,
        48.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496171",
      "kind": "tree",
      "position": [
        28.7,
        0,
        48.7
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496177",
      "kind": "tree",
      "position": [
        24.5,
        0,
        54.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496182",
      "kind": "tree",
      "position": [
        28.9,
        0,
        60.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496190",
      "kind": "tree",
      "position": [
        -45.5,
        0,
        76.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496192",
      "kind": "tree",
      "position": [
        -48.3,
        0,
        83.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496194",
      "kind": "tree",
      "position": [
        -12.3,
        0,
        95.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496195",
      "kind": "tree",
      "position": [
        -15.9,
        0,
        109
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496200",
      "kind": "tree",
      "position": [
        -17.8,
        0,
        116.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808496201",
      "kind": "tree",
      "position": [
        -19,
        0,
        120.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542223",
      "kind": "tree",
      "position": [
        41.7,
        0,
        90
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542289",
      "kind": "tree",
      "position": [
        14.6,
        0,
        105.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542334",
      "kind": "tree",
      "position": [
        10.1,
        0,
        107
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542408",
      "kind": "tree",
      "position": [
        45,
        0,
        119.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542418",
      "kind": "tree",
      "position": [
        23.9,
        0,
        121.8
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808542470",
      "kind": "tree",
      "position": [
        28.7,
        0,
        123.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983239",
      "kind": "tree",
      "position": [
        102.1,
        0,
        -56.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983240",
      "kind": "tree",
      "position": [
        100.9,
        0,
        -52.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983242",
      "kind": "tree",
      "position": [
        119.5,
        0,
        -45.6
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983243",
      "kind": "tree",
      "position": [
        92.5,
        0,
        -37.7
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983245",
      "kind": "tree",
      "position": [
        82.5,
        0,
        -14
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1808983249",
      "kind": "tree",
      "position": [
        84.7,
        0,
        -3.9
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1810200727",
      "kind": "tree",
      "position": [
        115.4,
        0,
        91.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1810200756",
      "kind": "tree",
      "position": [
        115.7,
        0,
        96.3
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1810200763",
      "kind": "tree",
      "position": [
        121.2,
        0,
        97.1
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1810200769",
      "kind": "tree",
      "position": [
        54.5,
        0,
        97.4
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    },
    {
      "id": "node/1810200787",
      "kind": "tree",
      "position": [
        126.6,
        0,
        98.5
      ],
      "height": null,
      "crownDiameter": null,
      "species": null,
      "genus": null
    }
  ],
  "pois": [
    {
      "id": "relation/1393926",
      "kind": "attraction",
      "name": "Rīgas Pils",
      "position": [
        42.9,
        0,
        112.9
      ],
      "priority": 100
    },
    {
      "id": "node/1294679116",
      "kind": "artwork",
      "name": "Lielais Kristaps",
      "position": [
        8.4,
        0,
        -37.1
      ],
      "priority": 98
    },
    {
      "id": "node/5124850509",
      "kind": "artwork",
      "name": "Eiropiāde",
      "position": [
        38.4,
        0,
        13.1
      ],
      "priority": 98
    },
    {
      "id": "node/12287802354",
      "kind": "museum",
      "name": "Latvijas Nacionālais vēstures muzejs",
      "position": [
        60.8,
        0,
        62.5
      ],
      "priority": 96
    },
    {
      "id": "node/1294679024",
      "kind": "information",
      "name": null,
      "position": [
        4.5,
        0,
        -30.9
      ],
      "priority": 92
    },
    {
      "id": "way/87493950",
      "kind": "place_of_worship",
      "name": "Rīgas Sāpju Dievmātes baznīca",
      "position": [
        91.9,
        0,
        29.3
      ],
      "priority": 66
    },
    {
      "id": "way/171926518",
      "kind": "place_of_worship",
      "name": "Anglikāņu baznīca",
      "position": [
        119,
        0,
        -28.9
      ],
      "priority": 66
    }
  ],
  "debug": {
    "paddedBbox": {
      "south": 56.94858650212001,
      "west": 24.097329947118816,
      "north": 56.951461097879985,
      "east": 24.10260085288118
    },
    "layers": [
      "roads",
      "buildings",
      "water",
      "landuse",
      "pois",
      "trees"
    ],
    "detail": "full",
    "rawCache": "miss",
    "rawStats": {
      "nodes": 1809,
      "ways": 186,
      "relations": 2,
      "roads": 109,
      "buildings": 38,
      "water": 2,
      "landuse": 34,
      "trees": 122,
      "pois": 16
    },
    "rawElements": 1997,
    "skippedRelations": 2
  }
}

]]

return game:GetService("HttpService"):JSONDecode(returnedData)
